# Generated by Django 5.2.4 on 2025-07-24 18:55

import subject_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0006_alter_student_locker_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(unique=True, validators=[subject_app.validators.validate_title_case])),
                ('professor', models.CharField(default='Mr. Cahan', validators=[subject_app.validators.validate_professor_name])),
                ('students', models.ManyToManyField(related_name='subject', to='student_app.student')),
            ],
        ),
    ]
