# Generated by Django 5.2.4 on 2025-07-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=100, unique=True)),
                ('personal_email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('locker_number', models.IntegerField(default=110, unique=True)),
                ('locker_combination', models.CharField(default='12-12-12', max_length=20)),
                ('good_student', models.BooleanField(default=True)),
            ],
        ),
    ]
