# Generated by Django 5.2.4 on 2025-07-23 15:46

import student_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_student_name_alter_student_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(default='12-12-12', max_length=20, validators=[student_app.validators.validate_combination_format]),
        ),
    ]
