# Generated by Django 5.2.4 on 2025-07-24 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade_app', '0001_initial'),
        ('student_app', '0007_student_subjects'),
        ('subject_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='a_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='subject_app.subject'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='student_app.student'),
        ),
    ]
